version: '3.5'

networks:
  githunter-net:
  githunter-scraper-net:
  mongo-net:

services:
  # Githunter-API
  githunter-api:
    build: ./githunter-api
    container_name: githunter-api
    image: githunter-api:1.0
    restart: always
    environment:
      GH_LOG_LEVEL: debug
      GH_GRAPHQL_GITHUB_URL: https://api.github.com/graphql
      GH_GRAPHQL_GITLAB_URL: https://gitlab.com/api/graphql
      GH_API_GITLAB_URL: https://gitlab.com/api/v4
      GH_SERVER_PORT: 3001
    ports:
      - 3001:3001
    networks:
      - githunter-net
    
  # Githunter-Data-Provider
  githunter-data-provider:
    build: ./githunter-data-provider
    container_name: githunter-data-provider
    image: githunter-data-provider:1.0
    restart: always
    ports:
      - 3333:3333
    networks:
      - mongo-net
      - githunter-net

  #Githunter-Bind-StarWS
  githunter-bind-starws:
    build: ./githunter-bind-starws
    container_name: githunter-bind-starws
    image: githunter-bind-starws:1.0
    restart: always
    ports:
      - 3005:3005
    networks:
      - githunter-net

  # Githunter-Scraper
  githunter-scraper:
    build: ./githunter-scraper
    container_name: githunter-scraper
    image: githunter-scraper:1.0
    restart: always
    ports:
      - 3002:3002
    networks:
      - githunter-scraper-net
      - githunter-net

  schellar:
    image: flaviostutz/schellar
    container_name: scraper-schellar
    environment:
      - CONDUCTOR_API_URL=http://conductor-server:8080/api
      - MONGO_ADDRESS=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "5"
    networks:
      - githunter-scraper-net
      - mongo-net

  conductor-server:
    build: ./githunter-scraper/conductor/server
    container_name: scraper-conductor-server
    image: conductor-server
    environment:
      - DYNOMITE_HOSTS=dynomite:8102:us-east-1c
      - ELASTICSEARCH_URL=elasticsearch:9300
      - LOADSAMPLE=false
      - PROVISIONING_UPDATE_EXISTING_TASKS=false
    ports:
      - 8080:8080
    restart: always
    networks:
      - githunter-scraper-net

  conductor-ui:
    image: flaviostutz/conductor-ui
    container_name: scraper-conductor-ui
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    ports:
      - 5000:5000
    networks:
      - githunter-scraper-net

  dynomite:
    image: flaviostutz/dynomite:0.7.5
    container_name: scraper-dynomite
    ports:
      - 8102:8102
    networks:
      - githunter-scraper-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: scraper-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - githunter-scraper-net
      
  # MongoDB for services Data-Provider & Schellar 
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/db/volume:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-net